language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem update --system
  - gem install sass --version ">=3.3.7"
  - gem install compass --version ">=0.12.3"
  - npm install --quiet -g grunt-cli karma
  - npm install
  - npm install -g bower
  - bower install -f

script: grunt default coveralls
notifications:
  email: false